import {PantryItem} from '../PantryItem';
import {writePantryItems} from './Filesystem';

export const examplePantryItems: PantryItem[] = [
  {
    barcode: 1,
    name: 'Coke (6 Pack)',
    price: '$4.99',
    expirationDate: '7/5/2022',
    lowStock: 1,
    quantity: 1,
    color: '#AABBCC',
  },
  {
    barcode: 2,
    name: 'Lays Chips',
    price: '$2.99',
    expirationDate: '8/3/2022',
    lowStock: 1,
    quantity: 2,
    color: '#36151E',
  },
  {
    barcode: 3,
    name: 'Toasted Crunch',
    price: '$3.99',
    expirationDate: '10/5/2022',
    lowStock: 2,
    quantity: 3,
    color: '#593F62',
  },
  {
    barcode: 4,
    name: 'Poland Spring',
    price: '$0.99',
    expirationDate: '12/31/2022',
    lowStock: 1,
    quantity: 12,
    color: '#247BA0',
  },
  {
    barcode: 5,
    name: 'Oreo Cookies',
    price: '$5.99',
    expirationDate: '11/7/2022',
    lowStock: 5,
    quantity: 12,
    color: '#8499B1',
  },
  {
    barcode: 6,
    name: 'Bread',
    price: '$0.99',
    expirationDate: '12/10/2022',
    lowStock: 2,
    quantity: 8,
    color: '#62B6CB',
  },
  {
    barcode: 7,
    name: 'Penne Pasta',
    price: '$3.99',
    expirationDate: '01/01/2023',
    lowStock: 3,
    quantity: 7,
    color: '#59A96A',
  },
  {
    barcode: 8,
    name: 'Brown Sugar',
    price: '$2.99',
    expirationDate: '8/5/2022',
    lowStock: 1,
    quantity: 2,
    color: '#56494E',
  },
  {
    barcode: 9,
    name: 'Strawberry Ice Cream',
    price: '$5.99',
    expirationDate: '6/9/2022',
    lowStock: 1,
    quantity: 4,
    color: '#272D2D',
  },
  {
    barcode: 10,
    name: 'Chicken thighs',
    price: '$7.99',
    expirationDate: '5/31/2022',
    lowStock: 2,
    quantity: 4,
    color: '#DB324D',
  },
  {
    barcode: 11,
    name: 'Grapes',
    price: '$4.99',
    expirationDate: '5/13/2022',
    lowStock: 1,
    quantity: 1,
    color: '#7F0799',
  },
  {
    barcode: 12,
    name: 'Orange Juice',
    price: '$3.99',
    expirationDate: '8/13/2022',
    lowStock: 1,
    quantity: 5,
    color: '#1A5E63',
  },
];

export function writeSamplePantryItems(): void {
  writePantryItems(examplePantryItems);
}
